# Development Configuration
development:
  server:
    port: 8080
    host: "localhost"
    base_url: "http://localhost:8080"
    gin_mode: "debug"
    read_timeout: "10s"
    write_timeout: "10s"
    idle_timeout: "15s"
  
  database:
    url: "postgresql://postgres:password@localhost:5432/ai_assistant_dev?schema=public"
    max_open_conns: 25
    max_idle_conns: 25
    conn_max_lifetime: "5m"
  
  redis:
    url: "redis://localhost:6379"
    max_retries: 3
    pool_size: 10
    min_idle_conns: 5
  
  logging:
    level: "debug"
    format: "json"
    output: "stdout"

# Production Configuration  
production:
  server:
    port: 8080
    host: "0.0.0.0"
    gin_mode: "release"
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
  
  database:
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_lifetime: "1h"
  
  redis:
    max_retries: 5
    pool_size: 50
    min_idle_conns: 10
  
  logging:
    level: "info"
    format: "json"
    output: "file"
    file_path: "/var/log/ai-assistant.log"

# Test Configuration
test:
  server:
    port: 8081
    gin_mode: "test"
  
  database:
    url: "postgresql://postgres:password@localhost:5432/ai_assistant_test?schema=public"
  
  redis:
    url: "redis://localhost:6379/1"
  
  logging:
    level: "warn"
    format: "text"
    output: "stdout"